name: Hospital Management System CI/CD

on:
  push:
    branches: [ "main", "dev" ]  # Runs on push to main and dev branches
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true  # Ensures all files are checked

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Run tests
        run: pytest  # Adjust for Django (pytest-django) or Flask

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy when merging to main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Application (Placeholder)
        run: echo "Deploying Hospital Management System..."
        # Add deployment steps here, e.g., SSH to server, upload files, restart services

